# -*- coding: utf-8 -*-
"""Landon Python Auction Project- .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTBZgwkhFn5aU3swQPFnfrG93-OlXA5R
"""

item_name = input("name the item name, ")

cost = float(input("how much does the item cost, "))
print(f"the {item_name} you are bidding for costs ${cost:.2f} ")


bid = 0

while cost > bid:
  answer = input("would you like to bid? (yes/no): ").lower()

  if answer == "yes":
    bid = float(input("how much are you bidding, "))

    if cost < bid:
      print(f"your bid = ${bid:.2f} was higher than the cost = ${cost:.2f} of the item, you've won the bid. ")
      print("congradulations, you've won the bid, please pay for your item withen 24hrs. ")
      break
    elif cost > bid:
      print(f"your bid = ${bid:.2f} was lower than the cost = ${cost:.2f} of the item, you've lost the bid. ")

    print("you’ve lost the bid")
  elif answer == "no":
    print("thank you for bidding, have a nice day, goodbye!")
    exit()
  else:
    print("invalid input, Please input 'yes' or 'no'. ")